name: worldcup_2026
schedule: "0 * * * *"
start_date: "2026-01-01"
catchup: false
concurrency: 1
max_active_steps: 1
retries: 3

default_connections:
  motherduck: "motherduck-fifa"

default:
  type: duckdb.sql
  rerun_cooldown: 20
